# Generated by Django 5.2 on 2026-07-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "ورودی"), (2, "خروجی")], default=1
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="files/%Y/%m/%d"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="order.ordertype",
                    ),
                ),
            ],
        ),
    ]
