# Generated by Django 5.2 on 2026-07-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0002_alter_file_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "ورودی"), (2, "خروجی")], default=2
            ),
        ),
    ]
