# Generated by Django 5.2 on 2026-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "ترجمه"), (2, "تایپ")], default=1
            ),
        ),
    ]
