# Generated by Django 5.2 on 2026-07-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0002_alter_file_order"),
        ("order", "0002_alter_order_order_type"),
        ("payment", "0002_alter_payment_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderType",
        ),
    ]
