# Generated by Django 5.2 on 2026-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_delete_ordertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputformat",
            name="factor",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="language",
            name="factor",
            field=models.FloatField(default=1),
        ),
    ]
