# Generated by Django 5.2 on 2026-07-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_inputformat_factor_language_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("factor", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "تکمیل شده"), (2, "درحال انجام"), (3, "پرداخت شده")],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="orders",
                to="order.ordertype",
            ),
        ),
    ]
