# Generated by Django 5.2 on 2026-07-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_ordertype_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderStatus",
        ),
    ]
