# Generated by Django 5.2 on 2026-07-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_delete_orderstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "تایپ"), (2, "ترجمه")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("COMPLETE", "تکمیل شده"),
                    ("PENDING", "درحال انجام"),
                    ("PAID", "پرداخت شده"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="OrderType",
        ),
    ]
