# Generated by Django 5.2 on 2026-07-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_order_type_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="description",
        ),
    ]
