# Generated by Django 5.2 on 2026-07-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_order_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("COMPLETE", "تکمیل شده"),
                    ("PENDING", "درحال انجام"),
                    ("PAID", "پرداخت شده"),
                    ("DELIVERED", "تحویل شده"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
    ]
