# Generated by Django 5.2 on 2026-07-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PROGRESS", "درحال انجام"),
                    ("READY", "آماده تحویل"),
                    ("DELIVERED", "تحویل شده"),
                ],
                default="PROGRESS",
                max_length=100,
            ),
        ),
    ]
