# Generated by Django 5.2 on 2026-07-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="input_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="order.inputformat",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="order.language",
            ),
        ),
    ]
